## Pandas

Used to manipulate datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
# overview of series: they are one column and multiple rows

# They are used for
# List
# Dict
# Numpy array

#### Creating Series and Data Frames from LIST, DICT etc

In [3]:
# creating a pandas series from a list
age = [25,30,35,60]
age_series = pd.Series(age, name='Age')

In [4]:
print(age_series)

0    25
1    30
2    35
3    60
Name: Age, dtype: int64

In [5]:
# Creating a pandas series from a dict
data_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400}
series_from_dict = pd.Series(data_dict)

In [6]:
print(series_from_dict)

a    100
b    200
c    300
d    400
dtype: int64

In [7]:
# Creating a pandas series from a numpy array
numpy_array = np.array([10,20,30,40,50,60,70,80,90,100])
series_from_array = pd.Series(numpy_array)

In [8]:
print(series_from_array)

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [9]:
# Creating a dataframe from a list. (Data frames are multiple rows and columns)
data_columns = ['CustomerID', 'Age', 'Income']
data = [[101, 25, 50000], [102, 30, 60000], [103, 35, 100000]]
customer_df = pd.DataFrame(data, columns=data_columns)

In [10]:
print(customer_df)

   CustomerID  Age  Income
0         101   25   50000
1         102   30   60000
2         103   35  100000

In [11]:
# Creating a dataframe from a dict.
dict_data = {'CustomerID': [101, 102, 103], 'Age': [25, 39, 35], 'Income':[50000, 60000, 100000]}
dict_df = pd.DataFrame(dict_data)

In [12]:
print(dict_df)

   CustomerID  Age  Income
0         101   25   50000
1         102   39   60000
2         103   35  100000

#### Basic operations in Pandas

In [13]:
# selecting a column
customer_df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [14]:
# selecting multiple columns
customer_df[['CustomerID', 'Age']]

   CustomerID  Age
0         101   25
1         102   30
2         103   35

In [15]:
# adding a new column
customer_df['Savings'] = customer_df['Income'] * 0.1 # 10%

customer_df

   CustomerID  Age  Income  Savings
0         101   25   50000   5000.0
1         102   30   60000   6000.0
2         103   35  100000  10000.0

In [16]:
# deleting a column
del customer_df['Savings']
customer_df

   CustomerID  Age  Income
0         101   25   50000
1         102   30   60000
2         103   35  100000

In [17]:
from datetime import datetime
# sample data for my dataframe
data = {
    'CustomerID': [101, 102, 103, 104, 105],
    'CustomerName': ['John Smith', 'Alice Johnson', 'Bob SMith', 'Eve Black', 'Jane Doe'],
    'Age': [25, 30, 35, 49, 56],
    'Income': [50000, 600000, 70000, 800000, 1000000],
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Amount': [1000, 1500, 2000, 2500, 3000],
    'Region': ['North', 'South', 'East', 'West','North'],
    'SalesDate': [datetime(2021, 1, 1), datetime(2021, 1, 2),datetime(2021, 1, 3),datetime(2021, 1, 4),
                  datetime(2021, 1, 5)]
}

# Create Dataframe
sales_df = pd.DataFrame(data)

In [18]:
sales_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
0         101     John Smith   25    50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

In [19]:
# Writing dataframe to csv
sales_df.to_csv('bank_sales_created.csv', index=False) # index=False to prevent the index insside the CSV

In [20]:
# Reading a csv file into a dataframe
sales = pd.read_csv(r'bank_sales.csv')

In [21]:
sales
# sales[['Age', 'Product']]

   CustomerID   CustomerName  Age  Income Product  Amount Region    SaleDate
0         101     John Smith   25   50000       A    1000  North  2021-01-01
1         102  Alice Johnson   30   60000       B    1500  South  2021-01-02
2         103      Bob Smith   35   70000       C    2000   East  2021-01-03
3         104      Eve Black   40   80000       D    2500   West  2021-01-04
4         105       Jane Doe   45   90000       E    3000  North  2021-01-05

In [22]:
# projecting & filtering
income_df = sales_df[['Income', 'Age']]
income_df

    Income  Age
0    50000   25
1   600000   30
2    70000   35
3   800000   49
4  1000000   56

In [23]:
# return only rows with income above 70k
high_income_df = sales_df[sales_df['Income'] > 70000]
high_income_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

#### Performing Total Aggregation

In [24]:
# sum
total_income = sales_df['Income'].sum()

total_income

np.int64(2520000)

In [25]:
# mean
average_age = sales_df['Age'].mean()
average_age

np.float64(39.0)

#### Joins

Merges

In [26]:
# Inner Join
sales_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
0         101     John Smith   25    50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

In [27]:
product_df = pd.DataFrame({'Product': ['A', 'B', 'C'], 'Category': ['Finance', 'Investment', 'Insurance']})
product_df

  Product    Category
0       A     Finance
1       B  Investment
2       C   Insurance

In [28]:
joined_df = pd.merge(sales_df, product_df, on='Product', how='inner')

In [29]:
print(joined_df)

   CustomerID   CustomerName  Age  Income Product  Amount Region  SalesDate  \
0         101     John Smith   25   50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30  600000       B    1500  South 2021-01-02
2         103      Bob SMith   35   70000       C    2000   East 2021-01-03

     Category
0     Finance
1  Investment
2   Insurance

In [30]:
# without pd
joined_df = sales_df.merge(product_df, on='Product', how='inner') # inner, outer, left, right
joined_df

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,Category
0,101,John Smith,25,50000,A,1000,North,2021-01-01,Finance
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,Investment
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,Insurance

In [31]:
# left join
left_join_df = pd.merge(sales_df, product_df, on='Product', how='left')
left_join_df

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,Category
0,101,John Smith,25,50000,A,1000,North,2021-01-01,Finance
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,Investment
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,Insurance
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,NaN
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,NaN

In [32]:
# right join
right_join_df = pd.merge(sales_df, customer_df, on='CustomerID', how='right')
right_join_df

,CustomerID,CustomerName,Age_x,Income_x,Product,Amount,Region,SalesDate,Age_y,Income_y
0,101,John Smith,25,50000,A,1000,North,2021-01-01,25,50000
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,30,60000
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,35,100000

In [33]:
customer_df

   CustomerID  Age  Income
0         101   25   50000
1         102   30   60000
2         103   35  100000

In [34]:
# outer join
outer_join_df = pd.merge(sales_df, product_df, on='Product', how='outer')
outer_join_df

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,Category
0,101,John Smith,25,50000,A,1000,North,2021-01-01,Finance
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,Investment
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,Insurance
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,NaN
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,NaN

#### Advanced Pandas Topics

In [35]:
# Reading an excel file
# excel_df = pd.read_excel(r'file')

In [36]:
# Handling missing values
# outer_join_df.info()
outer_join_df

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,Category
0,101,John Smith,25,50000,A,1000,North,2021-01-01,Finance
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,Investment
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,Insurance
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,NaN
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,NaN

In [37]:
# drop missing values
# outer_join_df.dropna(inplace=True)
# print(outer_join_df)

In [38]:
# filling missing values with apprpriate values
outer_join_df.fillna('Unknown', inplace=True)
outer_join_df

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,Category
0,101,John Smith,25,50000,A,1000,North,2021-01-01,Finance
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,Investment
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,Insurance
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,Unknown
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,Unknown

In [39]:
# Data Type Conversion/Data Standardization
outer_join_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    5 non-null      int64
 1   CustomerName  5 non-null      object
 2   Age           5 non-null      int64
 3   Income        5 non-null      int64
 4   Product       5 non-null      object
 5   Amount        5 non-null      int64
 6   Region        5 non-null      object
 7   SalesDate     5 non-null      datetime64[ns]
 8   Category      5 non-null      object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 492.0+ bytes

In [40]:
# Coverting Data type
outer_join_df['CustomerID'] = outer_join_df['CustomerID'].astype(str) # str, int
outer_join_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    5 non-null      object
 1   CustomerName  5 non-null      object
 2   Age           5 non-null      int64
 3   Income        5 non-null      int64
 4   Product       5 non-null      object
 5   Amount        5 non-null      int64
 6   Region        5 non-null      object
 7   SalesDate     5 non-null      datetime64[ns]
 8   Category      5 non-null      object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 492.0+ bytes

In [41]:
# Another method to convert to int
outer_join_df['CustomerID'] = pd.to_numeric(outer_join_df['CustomerID'], errors='coerce')
outer_join_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    5 non-null      int64
 1   CustomerName  5 non-null      object
 2   Age           5 non-null      int64
 3   Income        5 non-null      int64
 4   Product       5 non-null      object
 5   Amount        5 non-null      int64
 6   Region        5 non-null      object
 7   SalesDate     5 non-null      datetime64[ns]
 8   Category      5 non-null      object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 492.0+ bytes

In [42]:
# Grouping and Aggregating data
sales_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
0         101     John Smith   25    50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

In [43]:
grouped_df = sales_df.groupby('Product').agg({'Amount': ['sum', 'mean'], 'Age': 'mean'})
grouped_df

        Amount           Age
           sum    mean  mean
Product
A         1000  1000.0  25.0
B         1500  1500.0  30.0
C         2000  2000.0  35.0
D         2500  2500.0  49.0
E         3000  3000.0  56.0

In [44]:
# handling dupliccate values
sales_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
0         101     John Smith   25    50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

In [45]:
sales

   CustomerID   CustomerName  Age  Income Product  Amount Region    SaleDate
0         101     John Smith   25   50000       A    1000  North  2021-01-01
1         102  Alice Johnson   30   60000       B    1500  South  2021-01-02
2         103      Bob Smith   35   70000       C    2000   East  2021-01-03
3         104      Eve Black   40   80000       D    2500   West  2021-01-04
4         105       Jane Doe   45   90000       E    3000  North  2021-01-05

In [46]:
tables = [sales_df, sales]
sales_duplicates = pd.concat(tables)
sales_duplicates

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,SaleDate
0,101,John Smith,25,50000,A,1000,North,2021-01-01,NaN
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,NaN
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,NaN
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,NaN
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,NaN
0,101,John Smith,25,50000,A,1000,North,NaT,2021-01-01
1,102,Alice Johnson,30,60000,B,1500,South,NaT,2021-01-02
2,103,Bob Smith,35,70000,C,2000,East,NaT,2021-01-03
3,104,Eve Black,40,80000,D,2500,West,NaT,2021-01-04
4,105,Jane Doe,45,90000,E,3000,North,NaT,2021-01-05

In [47]:
sales_duplicates.drop_duplicates(subset='CustomerID', keep='first', inplace=True) # keep first duplicate
sales_duplicates

,CustomerID,CustomerName,Age,Income,Product,Amount,Region,SalesDate,SaleDate
0,101,John Smith,25,50000,A,1000,North,2021-01-01,NaN
1,102,Alice Johnson,30,600000,B,1500,South,2021-01-02,NaN
2,103,Bob SMith,35,70000,C,2000,East,2021-01-03,NaN
3,104,Eve Black,49,800000,D,2500,West,2021-01-04,NaN
4,105,Jane Doe,56,1000000,E,3000,North,2021-01-05,NaN

In [48]:
# sorting data
sorted_df =sales_df.sort_values(by='Income', ascending=False) # descending order
sorted_df

   CustomerID   CustomerName  Age   Income Product  Amount Region  SalesDate
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
0         101     John Smith   25    50000       A    1000  North 2021-01-01

In [49]:
# rename column
sales_df.rename(columns={'Income':'Salary'}, inplace=True)
sales_df

   CustomerID   CustomerName  Age   Salary Product  Amount Region  SalesDate
0         101     John Smith   25    50000       A    1000  North 2021-01-01
1         102  Alice Johnson   30   600000       B    1500  South 2021-01-02
2         103      Bob SMith   35    70000       C    2000   East 2021-01-03
3         104      Eve Black   49   800000       D    2500   West 2021-01-04
4         105       Jane Doe   56  1000000       E    3000  North 2021-01-05

In [50]:
# conditional selection
high_income_customer = sales[sales['Income'] > 80000]
high_income_customer

   CustomerID CustomerName  Age  Income Product  Amount Region    SaleDate
4         105     Jane Doe   45   90000       E    3000  North  2021-01-05

In [51]:
young_customers = sales[(sales['Age'] < 30) & (sales['Income'] > 50000) ]
young_customers

Empty DataFrame
Columns: [CustomerID, CustomerName, Age, Income, Product, Amount, Region, SaleDate]
Index: []

#### Slicing & Indexing in Pandas

Slicing can be done using loc and iloc method

###### Slicing using loc (label-based) 
###### Slicing using iloc (integer-based)

In [52]:
# Slice using loc(label-based)
label_based_slice = sales.loc[0:5, 'Income':'Region'] # sliced between Income and Region
label_based_slice

   Income Product  Amount Region
0   50000       A    1000  North
1   60000       B    1500  South
2   70000       C    2000   East
3   80000       D    2500   West
4   90000       E    3000  North

In [53]:
# slice using iloc(integer position-based)
position_based_slice = sales.iloc[0:5, 3:7] # Income - 3, Region - 7
position_based_slice

   Income Product  Amount Region
0   50000       A    1000  North
1   60000       B    1500  South
2   70000       C    2000   East
3   80000       D    2500   West
4   90000       E    3000  North

In [54]:
# slicing by index
sales

   CustomerID   CustomerName  Age  Income Product  Amount Region    SaleDate
0         101     John Smith   25   50000       A    1000  North  2021-01-01
1         102  Alice Johnson   30   60000       B    1500  South  2021-01-02
2         103      Bob Smith   35   70000       C    2000   East  2021-01-03
3         104      Eve Black   40   80000       D    2500   West  2021-01-04
4         105       Jane Doe   45   90000       E    3000  North  2021-01-05

In [55]:
sales.set_index('CustomerID', inplace=True)
sales

             CustomerName  Age  Income Product  Amount Region    SaleDate
CustomerID
101            John Smith   25   50000       A    1000  North  2021-01-01
102         Alice Johnson   30   60000       B    1500  South  2021-01-02
103             Bob Smith   35   70000       C    2000   East  2021-01-03
104             Eve Black   40   80000       D    2500   West  2021-01-04
105              Jane Doe   45   90000       E    3000  North  2021-01-05

In [56]:
slice_by_index = sales.loc[101:104]
slice_by_index

             CustomerName  Age  Income Product  Amount Region    SaleDate
CustomerID
101            John Smith   25   50000       A    1000  North  2021-01-01
102         Alice Johnson   30   60000       B    1500  South  2021-01-02
103             Bob Smith   35   70000       C    2000   East  2021-01-03
104             Eve Black   40   80000       D    2500   West  2021-01-04

In [57]:
# combining both methods
slice_by_both = sales.loc[101:105, sales.columns[1:4]]
slice_by_both

            Age  Income Product
CustomerID
101          25   50000       A
102          30   60000       B
103          35   70000       C
104          40   80000       D
105          45   90000       E

In [58]:
# resetting the index
sales.reset_index(inplace=True)
sales

   CustomerID   CustomerName  Age  Income Product  Amount Region    SaleDate
0         101     John Smith   25   50000       A    1000  North  2021-01-01
1         102  Alice Johnson   30   60000       B    1500  South  2021-01-02
2         103      Bob Smith   35   70000       C    2000   East  2021-01-03
3         104      Eve Black   40   80000       D    2500   West  2021-01-04
4         105       Jane Doe   45   90000       E    3000  North  2021-01-05

In [59]:
# setting multi-level indexing
sales.set_index(['Region', 'Product'], inplace=True)
sales

                CustomerID   CustomerName  Age  Income  Amount    SaleDate
Region Product
North  A               101     John Smith   25   50000    1000  2021-01-01
South  B               102  Alice Johnson   30   60000    1500  2021-01-02
East   C               103      Bob Smith   35   70000    2000  2021-01-03
West   D               104      Eve Black   40   80000    2500  2021-01-04
North  E               105       Jane Doe   45   90000    3000  2021-01-05

In [60]:
# slicing multi-level index

multi_level_slice = sales.loc['North', 'A']
multi_level_slice

CustomerID             101
CustomerName    John Smith
Age                     25
Income               50000
Amount                1000
SaleDate        2021-01-01
Name: (North, A), dtype: object